global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Reflection;
global using System.Threading.Tasks;
global using System.Text;
global using SahFederacijaLibrary.Entiteti;
global using SahFederacijaLibrary.DTOs;
global using NHibernate;
global using static SahFederacijaLibrary.Extensions;
global using System.Diagnostics.CodeAnalysis;